# Generated by Django 5.2.7 on 2026-01-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_sub',
        ),
    ]
